version: '2'
services:
  ops-jenkins:
    image: devsoftcom/home-jenkins
    container_name: ops-jenkins
    restart: always
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/leadel/jenkins_home:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
#  ops-teamcity:
#    image: devsoftcom/teamcity
#    container_name: ops-teamcity
#    volumes:
#    - /home/leadel/teamcity_data:/var/lib/teamcity
#    ports:
#    - "8111:8111"
#  ops-teamcity-agent:
#    image: devsoftcom/teamcity-agent
#    container_name: ops-teamcity-agent
#    links:
#    -  ops-teamcity:ops-teamcity
#    environment:
#    - TEAMCITY_SERVER=http://ops-teamcity:8111
