version: '2'
services:
  ops-jenkins:
    image: devsoftcom/home-jenkins
    restart: always
    container_name: ops-jenkins
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - /home/leadel/jenkins_home:/var/jenkins_home
